### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by guojieyuan-bd** [ROM-Knowledgeware/IPASign#19]
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 IPALibrary.CodeSignature.CodeSignatureHelper.ResignExecutable(MachObjectFile file, String bundleIdentifier, List`1 certificateChain, AsymmetricKeyEntry privateKey, Byte[] infoFileBytes, Byte[] codeResourcesBytes, EntitlementsFile entitlements)
   在 IPALibrary.IPAFile.ResignIPA(List`1 certificateChain, AsymmetricKeyEntry privateKey)
   在 IPASign.MainForm.ResignIPA(IPAFile ipaFile, Byte[] mobileProvisionBytes, Byte[] signingCertificateBytes, String certificatePassword, String outputIPAPath)
   在 IPASign.MainForm.btnSaveIPA_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by deepblue1004** [comment]
Same exception here

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at IPALibrary.CodeSignature.CodeSignatureHelper.ResignExecutable(MachObjectFile file, String bundleIdentifier, List`1 certificateChain, AsymmetricKeyEntry privateKey, Byte[] infoFileBytes, Byte[] codeResourcesBytes, EntitlementsFile entitlements)
   at IPALibrary.IPAFile.ResignIPA(List`1 certificateChain, AsymmetricKeyEntry privateKey)
   at IPASign.MainForm.ResignIPA(IPAFile ipaFile, Byte[] mobileProvisionBytes, Byte[] signingCertificateBytes, String certificatePassword, String outputIPAPath)
   at IPASign.MainForm.btnSaveIPA_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
