### ISSUE TITLE
SharpZipBaseException: Unknown block type 7

### ISSUE THREAD

**Issue by Xgamefactory** [ROM-Knowledgeware/IPASign#5]
```
ICSharpCode.SharpZipLib.SharpZipBaseException: Unknown block type 7

   at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.Decode()
   at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.Inflate(Byte[] buffer, Int32 offset, Int32 count)
   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Utilities.ByteUtils.CopyStream(Stream input, Stream output, Int64 count) in c:\D\prog\IPASign-master\Utilities\ByteUtils\ByteUtils.cs:line 78
   at Utilities.ByteReader.ReadBytes(Stream stream, Int32 count) in c:\D\prog\IPASign-master\Utilities\ByteUtils\ByteReader.cs:line 105
   at IPALibrary.IPAFile.GetFileBytes(String path) in c:\D\prog\IPASign-master\IPALibrary\IPAFile.cs:line 108
   at IPALibrary.IPAFile.GetInfoFileBytes() in c:\D\prog\IPASign-master\IPALibrary\IPAFile.cs:line 141
   at IPALibrary.IPAFile.GetInfoFile() in c:\D\prog\IPASign-master\IPALibrary\IPAFile.cs:line 151
   at IPALibrary.IPAFile.GetExecutableName() in c:\D\prog\IPASign-master\IPALibrary\IPAFile.cs:line 121
   at IPALibrary.IPAFile.GetExecutableBytes() in c:\D\prog\IPASign-master\IPALibrary\IPAFile.cs:line 157
   at IPALibrary.IPAFile.ResignIPA(List`1 certificateChain, AsymmetricKeyEntry privateKey) in c:\D\prog\IPASign-master\IPALibrary\IPAFile.cs:line 241
   at IPASign.MainForm.ResignIPA(IPAFile ipaFile, Byte[] mobileProvisionBytes, Byte[] signingCertificateBytes, String certificatePassword, String outputIPAPath) in c:\D\prog\IPASign-master\IPASign\MainForm.cs:line 245
   at IPASign.MainForm.btnSaveIPA_Click(Object sender, EventArgs e) in c:\D\prog\IPASign-master\IPASign\MainForm.cs:line 187
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at IPASign.Program.Main() in c:\D\prog\IPASign-master\IPASign\Program.cs:line 17

```

**Comment by ROM-Knowledgeware** [comment]
Hi, this is technically a [SharpZipLib](https://github.com/icsharpcode/SharpZipLib) issue with decompressing the IPA. could you upload the IPA?

**Comment by Xgamefactory** [comment]
ipa was created with adobe air sdk. this is our custormer project so we can't upload it.

**Comment by ROM-Knowledgeware** [comment]
Could you create an empty project and see if it shows the same problem with the IPA? I need a sample to send to SharpZipLib developers so they could fix the issue.

**Comment by Xgamefactory** [comment]
yes i will try with simple app and send you all datas ipa certificate provision

**Comment by sandorvasas** [comment]
+1 on this
