### ISSUE TITLE
PListNet.PListFormatException: 'Unknown node - XML tag "key"'

### ISSUE THREAD

**Issue by LGuilhas** [ROM-Knowledgeware/IPASign#7]
Hi,

I've build your tool with Visual Studio community 2017 but when I choose to resign the IPA I get the following exception:

PListNet.PListFormatException: 'Unknown node - XML tag "key"'

This is happening in the PLIstFile class constructor when reading the MemoryStream created from the mobile provisioning file

I've tried to update pListNet but the error remains and I'm positive the mobile provisioning is valid.
Any ideas?

PListNet.PListFormatException
  HResult=0x80131500
  Message=Unknown node - XML tag "key"
  Source=PListNet
  StackTrace:
   at PListNet.Internal.NodeFactory.Create(String tag)
   at PListNet.Nodes.ArrayNode.ReadXml(XmlReader reader)
   at PListNet.Nodes.ArrayNode.ReadXml(XmlReader reader)
   at PListNet.Nodes.DictionaryNode.ReadXml(XmlReader reader)
   at PListNet.Nodes.DictionaryNode.ReadXml(XmlReader reader)
   at PListNet.PList.LoadAsXml(Stream stream)
   at IPALibrary.PListFile..ctor(Byte[] plistBytes) in C:\Users\lgp\Desktop\IPASign-master\IPALibrary\PListFiles\PListFile.cs:line 32
   at IPALibrary.MobileProvisionPList..ctor(Byte[] plistBytes) in C:\Users\lgp\Desktop\IPASign-master\IPALibrary\MobileProvision\MobileProvisionPList.cs:line 20
   at IPALibrary.MobileProvisionFile..ctor(Byte[] fileBytes) in C:\Users\lgp\Desktop\IPASign-master\IPALibrary\MobileProvision\MobileProvisionFile.cs:line 31
   at IPASign.MainForm.ResignIPA(IPAFile ipaFile, Byte[] mobileProvisionBytes, Byte[] signingCertificateBytes, String certificatePassword, String outputIPAPath) in C:\Users\lgp\Desktop\IPASign-master\IPASign\MainForm.cs:line 196
   at IPASign.MainForm.btnSaveIPA_Click(Object sender, EventArgs e) in C:\Users\lgp\Desktop\IPASign-master\IPASign\MainForm.cs:line 182
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at IPASign.Program.Main() in C:\Users\lgp\Desktop\IPASign-master\IPASign\Program.cs:line 17

**Comment by ROM-Knowledgeware** [comment]
I haven't encountered this issue so far, I suggest you share the file / files causing the problem so I could recreate this. (either here or to my email: tal@kmrom.com )

**Comment by LGuilhas** [comment]
I've just sent you the mobile provision by email.
Let me know your findings.

**Comment by ROM-Knowledgeware** [comment]
PList-Net has an issue with empty arrays, I have [submitted a PR to their project](https://github.com/PList-Net/PList-Net/pull/12).
In addition, I have already [committed the fix](https://github.com/ROM-Knowledgeware/IPASign/commit/2311ab0c176290f2f6a4e410e8ce422a5be40d07) to IPASign.
